Squashed version of 480-pt2
commit fa855f8fce1d3dae2be736387255efa27a52672b
Author: MrD <the.ubik@gmail.com>
Date:   Mon May 4 00:31:35 2020 +0300

    SSS small fixups

commit b86e71b9a502da998fbc72783fe4074562e0909f
Author: MrD <the.ubik@gmail.com>
Date:   Fri Apr 24 16:32:27 2020 +0300

    Couple more loadData overrides gone

    Mopy/bash/game/oblivion/records.py:

    @@ -1407,4 +1397,5 @@ def dumpData(self,record,out):

    -            recordSetAttr('unused1',unpacked[22])

    -            values = recordGetAttr('skills') + [recordGetAttr('health')] + [
    -                recordGetAttr('unused1')] + recordGetAttr('attributes')

             MelFid('CNAM','iclass'),
    -        MelNpcData('DATA', '', ('skills', [0] * 21), 'health',
    -                   ('unused2', null2), ('attributes', [0] * 8)),
    +        MelNpcData(u'DATA', u'=21BH2s8B', (u'skills', [0 for __ in range(21)]),
    +                   u'health', (u'unused1', null2),
    +                   (u'attributes', [0 for __ in range(8)])),
             MelFid('HNAM','hair'),

    was adding unused2 (correctly) but getting/setting unused1 !!

    Mopy/bash/game/skyrim/records.py:
    Mopy/bash/game/fallout3/records.py:
    FFF data renames

commit 5db63f6a1380b0170fe90d4b6b19581ad6f87628
Author: Infernio <infernio@icloud.com>
Date:   Thu Apr 23 18:46:14 2020 +0200

    Drop almost all 'None' defaults

    Unless used with MelOptStructs, these just break the BP:

    mod_io.py  367 packSub: <bash.brec.mod_io.ModWriter object at 0x16FDA550>: Failed packing: CRDT, H2sfB3sI, (0, '\x00\x00', 0, 0, '\x00\x00\x00', None)
    mod_structs.py  106 dumpData: Error dumping data:
    Traceback (most recent call last):
      File "bash\brec\mod_structs.py", line 104, in dumpData
        element.dumpData(record,out)
      File "bash\brec\advanced_elements.py", line 840, in dumpData
        self._get_element_from_record(record).dumpData(record, out)
      File "bash\brec\basic_elements.py", line 564, in dumpData
        out.packSub(self.subType, self.struct_format, *values)
      File "bash\brec\mod_io.py", line 354, in packSub
        if values: data = struct_pack(data, *values)
    error: cannot convert argument to integer

    Some of these were being used with opt structs where the structs should
    have just been required, some were completely pointless. Surprised this
    didn't blow up early to be honest...

    Left comments on the ones that actually have a purpose.
    Semi-PEP8'd and prefixed the things I touched, as per usual.

    brec.MelRef3D, brec.MelXlod

    Had to touch them anyways, so decided to get rid of the duplication
    while I was at it.

    Fixup for Skyrim's MreAlch ENIT

    Again, happily mangling fids during merging.

    TES4, FO3, FNV: Minor fixups

    Went ahead and dropped the XGLB that does not exist in FO3/FNV, as the
    comment indicated. Also used MelReadOnly for SNDD in TES4, same as in
    FO3/FNV (could have sworn I already did that at some point...).

commit 628a74a88e944083d8e7e9949aab19fda434b230
Author: Infernio <infernio@icloud.com>
Date:   Thu Apr 23 00:15:03 2020 +0200

    Rewrite CTDA handling

    Much more centralized plus fixes several FormID mangling issues (Use
    Global flag, GetVATSValue parameters, missing OBSE functions).

    Since I had to edit the condition_function_data vars anyways to drop the
    third parameter (which xEdit always reads as an sint32, so specifying
    anything else there is pointless), took the opportunity to prefix them.

    Mopy/bash/brec/advanced_elements.py:
    Random misc fixups

commit 808e90a87f9eaf1674c51797ce07e75ea533fd0a
Author: Infernio <infernio@icloud.com>
Date:   Thu Apr 23 01:14:03 2020 +0200

    Interlude: Deduplicate FLST, document merge filtering

    Also expanded it to some others cause I felt like it :P

commit 71316058fbeb4518d4cc736615bf90a7e8e5cd14
Author: MrD <the.ubik@gmail.com>
Date:   Wed Apr 22 14:57:16 2020 +0300

    TopGrupHeader(GrupHeader): RRR

    Getting there!

    Mopy/bash/brec/common_records.py:
    One less pack, less uses of RecordHeader - sweet :)

    SSS writeGroup TTT XXX

    Note despite XXX is not more broken than before - was oblivion only and
    should still work for that . It duplicated some very nasty code - still
    not sure if extended properly for newer games - see FIXME

    ModReader thinning is particularly welcome - as well as reducing pack,
    label, type (is this faster than isinstance?), 'GRUP',size occurrences

    Re: writeGroups

    https://github.com/wrye-bash/wrye-bash/commit/665bc20c32ac3c2fdf854afad015840a2aec2a6a#commitcomment-38667338

    > Note that this is CELL children only, which we don't support for any
    > games using PBash yet, including Oblivion. So if it was horribly
    > broken, no one would have ever noticed :)

    > This explains some :P

    skip_top_group FFF rec header factory

    Encapsulate 'label', size and logic

    SSS skip_group

commit 2a74246423b936980d75577ba528e43473dae5b1
Author: MrD <the.ubik@gmail.com>
Date:   Wed Apr 22 02:16:38 2020 +0300

    btn_label

commit fce1ba8931656a3b0ab1f67bb1d23138a2acc7f2
Author: MrD <the.ubik@gmail.com>
Date:   Tue Apr 21 18:33:19 2020 +0300

    recordTypes -> valid_header_sigs EEE comments

    topTypes -> top_grup_sigs

commit eb70ee8d5354ba3de105d82fb56d8182c69f64c3
Author: Infernio <infernio@icloud.com>
Date:   Mon Feb 17 19:40:01 2020 +0100

    TES5: Refactor MelDobjDnam a bit

commit 0258eb3a9956ef5d130419943f18266916b0d75b
Author: MrD <the.ubik@gmail.com>
Date:   Mon Feb 17 16:24:48 2020 +0200

    WIP RecordHeader factory:

    Docstrings need more work, but headers should be further subclassed so...

    - WIP - rename some attributes and hunt down unrelated uses of fid etc
    - especially recType-> head_sig?
    - threw in some inlining mainly to reduce RecordHeader occurrences
    - optimized/sorted imports in the files I modified them

commit f0d663cbd607f75653ee009867ed69b93eb11f57
Author: MrD <the.ubik@gmail.com>
Date:   Tue Jan 21 04:13:19 2020 +0200

    WIP static structures:

    - should make creating those faster but most importantly we want
    MelStruct's to be as static as possible

commit c4095fbbe0f8816123df1a920ec55362956a1bd2
Author: MrD <the.ubik@gmail.com>
Date:   Thu Jan 23 16:54:42 2020 +0200

    WIP use precompiled struct unpackers:

    This is not so much about performance as for centralizing the handling
    of packers and unpackers so we can further extend/error check etc
    Note we should really only override loadData in brec - note similarity
    in some of the overrides. Sometimes using EAFP for errors (and avoiding
    if checks) could lead to cleaner code - note also using dictionaries to
    the same end.
    Re: optimization, note that apart from using precompiled Struct, we
    also bring stuff to local scope. This is done with the dunder prefixed
    function parameters - they are not meant to be used by clients.
    Unfortunately this introduces more `.unpack` occurrences - fortunately
    you can search for the calls with (?<!\))\.unpack\b

    MelCtda fixups SSS XXX TTT

    Mopy/bash/game/oblivion/records.py: This was blowing as:

    out.packSub('CTDA','B3sfI'+ record.form12 + '4s',

    is always writing record.unused2 - so form12 must be len 2. But then I
    must read a str in and not an int

    mod_io.py  368 packSub: <bash.brec.mod_io.ModWriter object at 0x27F4B1B0>: Failed packing: CTDA, B3sfIIi4s, (0, '\x00\x00\x00', 1.0, 71, 109893, 0, 0)
    Traceback (most recent call last):
      File "bash\brec\mod_io.py", line 355, in packSub
        if values: data = struct_pack(data, *values)
    error: argument for 's' must be a string

    However rest of files were using record.form12345 to pack *all* record
    attrs - this looks it would blow but for only the biggest possible sizes
    (32 skyrim, 28 fallout) - so was it intended to always write the bigger
    ones (as Oblivion) or should we chop off the attrs as I do? In that
    case we should not fill them with null4 and try packing them with 'I'..

    Mopy/bash/brec/mod_io.py: this was completely swallowed - should we raise?

    @@@ -366,4 -366,4 +366,9 @@@ class ModWriter(object)
                  bolt.deprint(u'%r: Failed packing: %s, %s, %s' % (
      <<<<<<< HEAD
     +                self, sub_rec_type, data, values))
     +            raise
      =======
    +                 self, sub_rec_type, data, values), traceback=True)
    +             # raise ??
      >>>>>>> abe4c1b0f... MelCtda fixups SSS XXX TTT

    lol :D

commit c5bc9dcf0360d9eac700d8c8350024fd18cc8955
Author: Infernio <infernio@icloud.com>
Date:   Wed Apr 22 22:29:21 2020 +0200

    Reraise packSub errors and other changes:

    Will be caught by MelSet.dumpData, where we can provide much more useful
    error info - plus now such a dump failure will abort the BP procedure.

    Utumno:

    Mopy/bash/record_groups.py: Chopping off `format`
    Mopy/bash/record_groups.py:
    Rename rec_sig will be used for recType - 0 occurrences remain
    Mopy/bash/record_groups.py:
    Mopy/bash/brec/advanced_elements.py: random prefixing
    Mopy/bash/patcher/patchers/importers.py: cell_fid renames

    patcher:

    getKeeper() -> don't return keepId

    Mopy/bash/patcher/patchers/multitweak_settings.py:
    Mopy/bash/patcher/patchers/special.py
    only uses I found quickly with keep(

    (?<!patchFile\.)\bgetKeeper\b just the definition

    Mopy/bash/record_groups.py:
    keepIds renames - should only be used for the patchFile attr
    record_groups.MobBase.loadData -> record_groups.MobBase.load_rec_group

    ÍCo-authored-by: MrD <the.ubik@gmail.com>

commit 06ba4f8c906798d6a3539fd644fcfae16228f96e
Author: MrD <the.ubik@gmail.com>
Date:   Thu Nov 21 18:02:11 2019 +0200

    fid renames - tracing down RecordHeader.fid WIP:

    Now you fid me now you don't - again in preparation for a header factory
     - need to be able to track down record.fid maybe a named tuple?

    regex(?<!(record|cell|gmst|race|npc|book)\.)\bfid\b

    rec_fid, fi, form_id etc are reserved for the usecases -
    Of course naming (alpha) is the purpose of this commit

    Mopy/bash/brec/mod_io.py:
    @@ -162,5 +162,5 @@ def unpack(ins):
             elif args[3] == 0: #groupType == 0 (Top Type)
    -            args = list(args)
                 str0 = struct_pack('I', args[2])
                 if str0 in RecordHeader.topTypes:
    +                args = list(args)
                     args[2] = str0

    Performance fix (Infernio: not really, else is an exception :P
    Ut: I know, well better scoping then :P)

    SSS more consistent fid renames

    - form_id is nice and should maybe go to a better use when the dust
    settles - for now I used it as a method parameter - easily
    replaceable by say form_id_, there were no occurrences in parent
    - rec_fid is also nice and also no occurrences in parent. However there
    are too many usages so let's wait for parsers/tweaks refactoring
    that might reduce those
    - fi is ugly - and same applies for occurrences/usages

commit c5cd5442e0367c8a0d5f00fb9d46a903e2489dd7
Author: MrD <the.ubik@gmail.com>
Date:   Sat Nov 9 00:31:58 2019 +0100

    Refer to RecordHeader directly - prefixing strings:

    Hunting down RecordHeader usages, in preparation for a header factory.
    I introduced 'header_type', for the game files usages - I had tried
    other names like rec_type (wrong) and header_type_ (too long) so I
    settled to header_type, renaming the (private) ones in cosaves/bsas.
    'type' is currently widely used in records (but also BAIN, belt, etc)
    meaning different types of types - we should eventually confine its
    use to what python uses it for, namely the `type` of an object. This
    will improve readability in affected areas (in records code 'sig' could
    be used instead, in BAIN 'itype', etc), and help us add proper typing in
    py3. Of course manipulating types directly should be moderately avoided.
    Note inlines and `hsize` are alpha

    I prefixed stings (note morrowind was prefixed) sooner than later, as
    this code will be changed again soon.

    Mopy/bash/brec/mod_io.py:

    Note I reverted some u'' prefixes from
    d21d4f9ddeb933e6255eccacdadcb39a42dae41d still bytes IIUC

commit bb84bc9c40708ea02b2a3b7352a3537726001797
Author: MrD <the.ubik@gmail.com>
Date:   Fri Apr 24 22:57:55 2020 +0300

    rename from Mopy/bash/brec/mod_structs.py -> record_structs.py

commit 9514a34a6c02a225f83d96d9e3fa7a47cf483b5b
Author: Infernio <infernio@icloud.com>
Date:   Sat Apr 18 03:06:38 2020 +0200

    Split brec to a package

    Names could use some work, but editing is much nicer. Did it in a single
    commit so I wouldn't have to bother with fixing imports several times
    over.

    Only had to fix one circular dependency (arose due to the way I designed
    the distributor API, could be fixed by changing it - but I like the way
    it works :)).

    Added myself as author of advanced_elements, since that file is 100% my
    code - the rest is a mix of my code and code that's been around for a
    long time.

commit 991bca2126c917f9c8a0a64a7ede8a129b355832
Author: Infernio <infernio@icloud.com>
Date:   Sat Apr 18 02:56:33 2020 +0200

    TES5: Rewrite ACHR definition

    Was just curious why Enderal was failing to verify records before it got
    to NAVM (which we obviously don't support yet), then I noticed this was
    the last usage of MelSortedFidList - gone now :)

commit 1f8a55f89cc0859a2d47248d489757bab586be54
Author: Infernio <infernio@icloud.com>
Date:   Sat Apr 11 04:11:57 2020 +0200

    TES4: Support OBME for PBash

    Yay, more rabbit holes! Started going down this one when someone on
    Discord reported that one particular plugin didn't properly behave when
    tagged with 'Text'. Spent way too long trying to find a bug in our
    patcher, when I should have taken a look in the BashBugDump, where the
    cause was plain as day: 'Unexpected subrecord SPEL.OBME'.

    So... I went ahead and implemented it :)
    CBash already supports this, and now PBash does too. Very limited
    support though, in that we support reading, writing and patching them,
    but I made all patchers and tweaks that do anything special with effects
    just skip these records for now. We can always revisit and enable that
    behavior later.

commit 1309768ddc79fb7da088894604fd4c3a95c5bb7e
Author: Infernio <infernio@icloud.com>
Date:   Sat Apr 11 02:43:26 2020 +0200

    MelUnion: Proper fallback support

    Was completely broken in many cases. We just happened to not use it for
    any of those. Whoops.

    Also dropped MelSet.firstFull, unused since the MelFull0 removal.

commit 0e901078335ba319d29ef1040627347afa123361
Author: Infernio <infernio@icloud.com>
Date:   Sun Oct 6 03:06:35 2019 +0200

    Improve 'Test Full Record Definitions'

    This link is invaluable for figuring out which parts of the record
    definitions are still broken, but the way it provides feedback is far
    from ideal. This makes it at least show a popup indicating success or
    failure.

    Had this sitting around for a long time on a half-forgotten branch.

commit 4187df146bf407358ad6036fa54017dcce8fa605
Author: Infernio <infernio@icloud.com>
Date:   Wed Mar 25 23:09:34 2020 +0100

    Rewrite FACT implementations for all games

    Finally fixes it properly for Skyrim - the missing PLVD began looking
    remarkably familar when I started writing it :P

    For all other games, we PEP8 it, get rid of terrible names and prefix
    all touched strings.

    As a result, FACT can now be merged and patched by Skyrim's Names
    patcher again (in preparation for the Relations patcher coming in
    inf-312-parser-abc).

commit 556ad07fcb53e1b17b92c03879f0870eecef617d
Author: Infernio <infernio@icloud.com>
Date:   Mon Mar 23 13:56:46 2020 +0100

    Prefix classType class vars

    classType = '([A-Z_\d]{4})' -> classType = b'$1'

commit d9d3a993bca79936d22adaa831320296109d68c5
Author: Infernio <infernio@icloud.com>
Date:   Mon Feb 10 18:48:59 2020 +0100

    TES5: Drop dumpExtra

    This gets rid of one of the ugliest remaining hacks in WB's records
    code. It only had 5 remaining usages in Skyrim's record definitions,
    but slowed down loading and dumping for all MelStructs in all games.

    Also took the opportunity to drop MelWaterHeight using MelUnion while I
    was editing Skyrim's MreCell.

    Explanations:
     1. For MreSopm, I went through and checked all vanilla records as well
        as what the CK creates. Turns out it's always 3 bytes. Also reported
        it to the xEdit team, so this wil be fixed in the next release.
     2. For MreCell, see my comment there - unneeded and likely unused.
     3. For MreLctn, I added a new keyword argument to MelArray, which
        allows it to process a single, static, fixed-size element before
        the repeating element.

    Included py3 division edits to brec.py to simplify conflicts.