Squashed version of 480-pt2
commit d3561ba9e10554088b906cf0205879069152e86c
Author: MrD <the.ubik@gmail.com>
Date:   Fri May 1 15:36:00 2020 +0300

    fixup 480 Rename rec_sig will be used for recType - 0 occurrences remain SSS

commit 1351b13df6d0ad2b7d0c49e3f4cddcfc7cdf8fe5
Author: MrD <the.ubik@gmail.com>
Date:   Tue Apr 28 20:59:32 2020 +0300

    fixup! 480-pt2

    Mopy/bash/brec/advanced_elements.py: prefixing FFF

commit 34690913c676f0cdabaada7750e4ba5eb3b879d3
Author: MrD <the.ubik@gmail.com>
Date:   Fri Apr 24 16:06:48 2020 +0300

    fixup!     Rewrite CTDA handling

commit 92ee8e3b69368e035b6beaeb3062430553ea0381
Author: Infernio <infernio@icloud.com>
Date:   Thu Apr 23 18:46:14 2020 +0200

    Drop almost all 'None' defaults

    Unless used with MelOptStructs, these just break the BP:

    mod_io.py  367 packSub: <bash.brec.mod_io.ModWriter object at 0x16FDA550>: Failed packing: CRDT, H2sfB3sI, (0, '\x00\x00', 0, 0, '\x00\x00\x00', None)
    mod_structs.py  106 dumpData: Error dumping data:
    Traceback (most recent call last):
      File "bash\brec\mod_structs.py", line 104, in dumpData
        element.dumpData(record,out)
      File "bash\brec\advanced_elements.py", line 840, in dumpData
        self._get_element_from_record(record).dumpData(record, out)
      File "bash\brec\basic_elements.py", line 564, in dumpData
        out.packSub(self.subType, self.struct_format, *values)
      File "bash\brec\mod_io.py", line 354, in packSub
        if values: data = struct_pack(data, *values)
    error: cannot convert argument to integer

    Some of these were being used with opt structs where the structs should
    have just been required, some were completely pointless. Surprised this
    didn't blow up early to be honest...

    Left comments on the ones that actually have a purpose.
    Semi-PEP8'd and prefixed the things I touched, as per usual.

    brec.MelRef3D, brec.MelXlod

    Had to touch them anyways, so decided to get rid of the duplication
    while I was at it.

    Fixup for Skyrim's MreAlch ENIT

    Again, happily mangling fids during merging.

    TES4, FO3, FNV: Minor fixups

    Went ahead and dropped the XGLB that does not exist in FO3/FNV, as the
    comment indicated. Also used MelReadOnly for SNDD in TES4, same as in
    FO3/FNV (could have sworn I already did that at some point...).

commit 581ca298f1a8a84fd570ebc9e2ae6e4c501f6bd8
Author: Infernio <infernio@icloud.com>
Date:   Thu Apr 23 00:15:03 2020 +0200

    Rewrite CTDA handling

    Much more centralized plus fixes several FormID mangling issues (Use
    Global flag, GetVATSValue parameters, missing OBSE functions).

    Since I had to edit the condition_function_data vars anyways to drop the
    third parameter (which xEdit always reads as an sint32, so specifying
    anything else there is pointless), took the opportunity to prefix them.

    Mopy/bash/brec/advanced_elements.py:
    Random misc fixups

commit f0a0ccbafe3495fae6d21b432cda055ab3d3a8e7
Author: Infernio <infernio@icloud.com>
Date:   Thu Apr 23 01:14:03 2020 +0200

    Interlude: Deduplicate FLST, document merge filtering

    Also expanded it to some others cause I felt like it :P

commit f387c751cc0f7552f2b500cf0c432aa3ce5b6f24
Author: MrD <the.ubik@gmail.com>
Date:   Wed Apr 22 15:39:17 2020 +0300

    SSS writeGroup TTT XXX

    Note despite XXX is not more broken than before - was oblivion only and
    should still work for that . It duplicated some very nasty code - still
    not sure if extended properly for newer games - see FIXME

    ModReader thinning is particularly welcome - as well as reducing pack,
    label, type (use isinstance plz), 'GRUP',size occurrences

commit f54f62dd7c1b6751fbfb0d06a5eb64fcec9d3f47
Author: MrD <the.ubik@gmail.com>
Date:   Wed Apr 22 15:12:17 2020 +0300

    SSS out.write(GrupHeader

    One less pack, less uses of RecordHeader - sweet :)

commit fd14ce90c9233f52c795a0a1dce5d9fff7d47928
Author: MrD <the.ubik@gmail.com>
Date:   Wed Apr 22 14:57:16 2020 +0300

    TopGrupHeader(GrupHeader):

    Getting there :)

commit df473b968985addbc21e46e927ccc6280e0ed0cb
Author: MrD <the.ubik@gmail.com>
Date:   Wed Apr 22 02:16:38 2020 +0300

    btn_label

commit 1b41e7b0bf0c096339b4a8074505133b1d245920
Author: MrD <the.ubik@gmail.com>
Date:   Tue Apr 21 19:00:07 2020 +0300

    topTypes -> top_grup_sigs

commit 8e869ab06d47ffaa50cccb2d514a2503b834c404
Author: MrD <the.ubik@gmail.com>
Date:   Tue Apr 21 18:33:19 2020 +0300

    recordTypes -> valid_header_sigs

commit 2e88b86c8fd8bd924d250f8f7f379b985a56dd0d
Author: Infernio <infernio@icloud.com>
Date:   Mon Feb 17 19:40:01 2020 +0100

    TES5: Refactor MelDobjDnam a bit

commit bfdbe97ddc99d17b98eae96bd2bab44a415f938e
Author: MrD <the.ubik@gmail.com>
Date:   Mon Feb 17 16:24:48 2020 +0200

    WIP RecordHeader factory: TTT

    Docstrings need more work, but headers should be further subclassed so...

    - WIP - rename some attributes and hunt down unrelated uses of fid etc
    - especially recType-> head_sig?
    - threw in some inlining mainly to reduce RecordHeader occurrences
    - optimized/sorted imports in the files I modified them

    squash!     WIP RecordHeader factory:

    TTT and check TODOs

    Mopy/bash/record_groups.py:
    TTT

    @@ -59,9 +59,10 @@ def __init__(self, header, loadFactory, ins=None, do_unpack=False):
             self.header = header
    -        if header.recType == 'GRUP':
    -            self.size,self.label,self.groupType,self.stamp = (
    -                header.size,header.label,header.groupType,header.stamp)
    +        self.size = header.size
    +        if header.recType == b'GRUP': # TODO(ut) should MobBase used for GRUP headers? deprint here <---- note todo
    +            self.label, self.groupType, self.stamp = (
    +                header.label, header.groupType, header.stamp)
             else:
                 # Yes it's weird, but this is how it needs to work
    -            self.size,self.label,self.groupType,self.stamp = (
    -                header.size,header.flags1,header.fid,header.flags2)
    +            self.label, self.groupType, self.stamp = (
    +                header.flags1, header.fid, header.flags2)
             self.debug = False

    EEE rec_type -> header_sig

    Mopy/bash/exception.py: started renaming the rec_type ended up uprooting
    those format calls - rest of the branch should explain why. Dropped
    ModReadError.rec_type seems unused TTT

commit 193f7c26f4da08bbca0a39888b317bb13f94f90a
Author: MrD <the.ubik@gmail.com>
Date:   Tue Jan 21 04:13:19 2020 +0200

    WIP static structures:

    - should make creating those faster but most importantly we want
    MelStruct's to be as static as possible

commit 26ecafbcacee9e226f2abe7799177918c8241327
Author: Infernio <infernio@icloud.com>
Date:   Wed Apr 22 22:29:21 2020 +0200

    FFF Reraise packSub errors

    Will be caught by MelSet.dumpData, where we can provide much more useful
    error info - plus now such a dump failure will abort the BP procedure.

commit df57838c7090ce5d106977b675aa4c55224dcab1
Author: MrD <the.ubik@gmail.com>
Date:   Thu Jan 23 16:54:42 2020 +0200

    WIP use precompiled struct unpackers:

    This is not so much about performance as for centralizing the handling
    of packers and unpackers so we can further extend/error check etc
    Note we should really only override loadData in brec - note similarity
    in some of the overrides. Sometimes using EAFP for errors (and avoiding
    if checks) could lead to cleaner code - note also using dictionaries to
    the same end.
    Re: optimization, note that apart from using precompiled Struct, we
    also bring stuff to local scope. This is done with the dunder prefixed
    function parameters - they are not meant to be used by clients.
    Unfortunately this introduces more `.unpack` occurrences - fortunately
    you can search for the calls with (?<!\))\.unpack\b

    MelCtda fixups SSS XXX TTT

    Mopy/bash/game/oblivion/records.py: This was blowing as:

    out.packSub('CTDA','B3sfI'+ record.form12 + '4s',

    is always writing record.unused2 - so form12 must be len 2. But then I
    must read a str in and not an int

    mod_io.py  368 packSub: <bash.brec.mod_io.ModWriter object at 0x27F4B1B0>: Failed packing: CTDA, B3sfIIi4s, (0, '\x00\x00\x00', 1.0, 71, 109893, 0, 0)
    Traceback (most recent call last):
      File "bash\brec\mod_io.py", line 355, in packSub
        if values: data = struct_pack(data, *values)
    error: argument for 's' must be a string

    However rest of files were using record.form12345 to pack *all* record
    attrs - this looks it would blow but for only the biggest possible sizes
    (32 skyrim, 28 fallout) - so was it intended to always write the bigger
    ones (as Oblivion) or should we chop off the attrs as I do? In that
    case we should not fill them with null4 and try packing them with 'I'..

    Mopy/bash/brec/mod_io.py: this was completely swallowed - should we raise?

    @@@ -366,4 -366,4 +366,9 @@@ class ModWriter(object)
                  bolt.deprint(u'%r: Failed packing: %s, %s, %s' % (
      <<<<<<< HEAD
     +                self, sub_rec_type, data, values))
     +            raise
      =======
    +                 self, sub_rec_type, data, values), traceback=True)
    +             # raise ??
      >>>>>>> abe4c1b0f... MelCtda fixups SSS XXX TTT

    lol :D

commit f076e6dd558590ffb0a37dd5af23593f9da5c76a
Author: MrD <the.ubik@gmail.com>
Date:   Thu Nov 21 18:03:51 2019 +0200

    Does keep need to return the fid? Untested!! XXX

    only uses I found quickly with keep(

    (?<!patchFile\.)\bgetKeeper\b just the definition

commit 0137715ff77172273d3b65ad2d4e2d19b49f6935
Author: MrD <the.ubik@gmail.com>
Date:   Thu Jan 23 01:42:18 2020 +0200

    record_groups.MobBase.loadData -> record_groups.MobBase.load_rec_group

    Mopy/bash/record_groups.py:
    keepIds renames - should only be used for the patchFile attr

commit 2f15ae4f1a796642000dc23d3cf1d4da7de1293d
Author: MrD <the.ubik@gmail.com>
Date:   Mon Feb 17 14:40:06 2020 +0200

    Chopping off `format`, struct_fmt to unicode

    MelArray -> :type element: MelStruct ? XXX

    @@ -1414,3 +1414,3 @@ def __init__(self, array_attr, element, prelude=None):
                 loaded and dumped by.
    -        :type element: MelBase
    +        :type element: MelStruct
             :param prelude: An optional element that will be loaded and dumped once
    Infernio: Dropped type -> MelStruct part, there are already
    MelArray(MelFid) usages - plus conceptually we want it to be able to
    support any fixed-size element.

commit e4996aa72ecab4148473dc6a5410206e3f557e0c
Author: MrD <the.ubik@gmail.com>
Date:   Thu Nov 21 18:02:11 2019 +0200

    fid renames - tracing down RecordHeader.fid WIP:

    Now you fid me now you don't - again in preparation for a header factory
     - need to be able to track down record.fid maybe a named tuple?

    regex(?<!(record|cell|gmst|race|npc|book)\.)\bfid\b

    rec_fid, fi, form_id etc are reserved for the usecases -
    Of course naming (alpha) is the purpose of this commit

    Mopy/bash/brec/mod_io.py:
    @@ -162,5 +162,5 @@ def unpack(ins):
             elif args[3] == 0: #groupType == 0 (Top Type)
    -            args = list(args)
                 str0 = struct_pack('I', args[2])
                 if str0 in RecordHeader.topTypes:
    +                args = list(args)
                     args[2] = str0

    Performance fix (Infernio: not really, else is an exception :P
    Ut: I know, well better scoping then :P)

    SSS more consistent fid renames

    - form_id is nice and should maybe go to a better use when the dust
    settles - for now I used it as a method parameter - easily
    replaceable by say form_id_, there were no occurrences in parent
    - rec_fid is also nice and also no occurrences in parent. However there
    are too many usages so let's wait for parsers/tweaks refactoring
    that might reduce those
    - fi is ugly - and same applies for occurrences/usages

commit b50ccc51374b962cc691c8f8fceba6622c82887b
Author: MrD <the.ubik@gmail.com>
Date:   Sat Nov 9 00:31:58 2019 +0100

    Refer to RecordHeader directly - prefixing strings:

    Hunting down RecordHeader usages, in preparation for a header factory.
    I introduced 'header_type', for the game files usages - I had tried
    other names like rec_type (wrong) and header_type_ (too long) so I
    settled to header_type, renaming the (private) ones in cosaves/bsas.
    'type' is currently widely used in records (but also BAIN, belt, etc)
    meaning different types of types - we should eventually confine its
    use to what python uses it for, namely the `type` of an object. This
    will improve readability in affected areas (in records code 'sig' could
    be used instead, in BAIN 'itype', etc), and help us add proper typing in
    py3. Of course manipulating types directly should be moderately avoided.
    Note inlines and `hsize` are alpha

    I prefixed stings (note morrowind was prefixed) sooner than later, as
    this code will be changed again soon.

    Mopy/bash/brec/mod_io.py:

    Note I reverted some u'' prefixes from
    d21d4f9ddeb933e6255eccacdadcb39a42dae41d still bytes IIUC

commit 14104432dd4caac88a1d8b92fa24c9fceb84086d
Author: MrD <the.ubik@gmail.com>
Date:   Fri Apr 24 22:57:55 2020 +0300

    rename from Mopy/bash/brec/mod_structs.py -> record_structs.py

commit dd628f42bcf637a710886f22b543ed9da7109664
Author: Infernio <infernio@icloud.com>
Date:   Sat Apr 18 03:06:38 2020 +0200

    Split brec to a package

    Names could use some work, but editing is much nicer. Did it in a single
    commit so I wouldn't have to bother with fixing imports several times
    over.

    Only had to fix one circular dependency (arose due to the way I designed
    the distributor API, could be fixed by changing it - but I like the way
    it works :)).

    Added myself as author of advanced_elements, since that file is 100% my
    code - the rest is a mix of my code and code that's been around for a
    long time.

commit 97f5f2f9922b180c51e1d94cfdd04dbf6f5a8073
Author: Infernio <infernio@icloud.com>
Date:   Sat Apr 18 02:56:33 2020 +0200

    TES5: Rewrite ACHR definition

    Was just curious why Enderal was failing to verify records before it got
    to NAVM (which we obviously don't support yet), then I noticed this was
    the last usage of MelSortedFidList - gone now :)

commit 1074068b2dc5965160c9053a89ceeef49e8a5126
Author: Infernio <infernio@icloud.com>
Date:   Sat Apr 11 04:11:57 2020 +0200

    TES4: Support OBME for PBash

    Yay, more rabbit holes! Started going down this one when someone on
    Discord reported that one particular plugin didn't properly behave when
    tagged with 'Text'. Spent way too long trying to find a bug in our
    patcher, when I should have taken a look in the BashBugDump, where the
    cause was plain as day: 'Unexpected subrecord SPEL.OBME'.

    So... I went ahead and implemented it :)
    CBash already supports this, and now PBash does too. Very limited
    support though, in that we support reading, writing and patching them,
    but I made all patchers and tweaks that do anything special with effects
    just skip these records for now. We can always revisit and enable that
    behavior later.

commit ecbcf88bb8e50ac77f9d694e6d97308f3bf240cd
Author: Infernio <infernio@icloud.com>
Date:   Sat Apr 11 02:43:26 2020 +0200

    MelUnion: Proper fallback support

    Was completely broken in many cases. We just happened to not use it for
    any of those. Whoops.

    Also dropped MelSet.firstFull, unused since the MelFull0 removal.

commit 902ed09b40a07095c17e0753570bfe6516f7b68e
Author: Infernio <infernio@icloud.com>
Date:   Sun Oct 6 03:06:35 2019 +0200

    Improve 'Test Full Record Definitions'

    This link is invaluable for figuring out which parts of the record
    definitions are still broken, but the way it provides feedback is far
    from ideal. This makes it at least show a popup indicating success or
    failure.

    Had this sitting around for a long time on a half-forgotten branch.

commit 4ce81d2cde1bfe1d231f01e6d0ee7b9407ceec7f
Author: Infernio <infernio@icloud.com>
Date:   Wed Mar 25 23:09:34 2020 +0100

    Rewrite FACT implementations for all games

    Finally fixes it properly for Skyrim - the missing PLVD began looking
    remarkably familar when I started writing it :P

    For all other games, we PEP8 it, get rid of terrible names and prefix
    all touched strings.

    As a result, FACT can now be merged and patched by Skyrim's Names
    patcher again (in preparation for the Relations patcher coming in
    inf-312-parser-abc).

commit bccbc056da5e521021dedd6cba1e0968107ac3c2
Author: Infernio <infernio@icloud.com>
Date:   Mon Mar 23 13:56:46 2020 +0100

    Prefix classType class vars

    classType = '([A-Z_\d]{4})' -> classType = b'$1'

commit 2e10314fef327ddc57682bee2012d13f6a2150c3
Author: Infernio <infernio@icloud.com>
Date:   Mon Feb 10 18:48:59 2020 +0100

    TES5: Drop dumpExtra

    This gets rid of one of the ugliest remaining hacks in WB's records
    code. It only had 5 remaining usages in Skyrim's record definitions,
    but slowed down loading and dumping for all MelStructs in all games.

    Also took the opportunity to drop MelWaterHeight using MelUnion while I
    was editing Skyrim's MreCell.

    Explanations:
     1. For MreSopm, I went through and checked all vanilla records as well
        as what the CK creates. Turns out it's always 3 bytes. Also reported
        it to the xEdit team, so this wil be fixed in the next release.
     2. For MreCell, see my comment there - unneeded and likely unused.
     3. For MreLctn, I added a new keyword argument to MelArray, which
        allows it to process a single, static, fixed-size element before
        the repeating element.

    Included py3 division edits to brec.py to simplify conflicts.