actor_importer_attrs -> never a tuple in there?
Note that

{}[[]]
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: unhashable type: 'list'

so the isinstance(attr, (list, tuple, set)): make not much sense

fixup!     actor_importer_attrs -> never a tuple in there?