Squashed version of inf-beta6-fixes
commit 51b2a6eeb6756ccfe5b9f340cb9a0fc66bf2d3d0
Author: Infernio <infernio@icloud.com>
Date:   Sat May 2 18:02:50 2020 +0200

    Fix Duplicate not updating cosaves

    Would show the new copy as having mismatched masters, because the cosave
    only got attached on tabbing out and back in.

commit 056826225becd81b47174680c5c9c0e8ade57f70
Author: Infernio <infernio@icloud.com>
Date:   Sat May 2 17:33:32 2020 +0200

    cosaves: Support DATA chunks

    Added by SOS to Skyrim LE/SE. No, not Sounds of Skyrim, the other one.
    Need to support this since it contains a list of mod names that have to
    be remapped when we change a save master.

    Features the worst way to store integers I've ever seen, namely by
    converting them to strings and then writing the literal ASCII bytes of
    the string out. Who doesn't love needing O(log n) space to store an int?

commit d986f4c2edeafef773f1d4a2bd2671de85b37f24
Author: Infernio <infernio@icloud.com>
Date:   Sat May 2 01:07:15 2020 +0200

    Fix traceback on Ctrl+Arrow with nothing selected

    Traceback (most recent call last):
      File "bash\gui\events.py", line 166, in _post
        result = listener(*listener_args)
      File "bash\basher\__init__.py", line 1001, in OnChar
        newIndex = chunk[0] + moveMod
    IndexError: list index out of range

commit e6f16f78930cf9e1232b57c9e53e038bcd3cacab
Author: Infernio <infernio@icloud.com>
Date:   Fri May 1 17:38:18 2020 +0200

    bain: Rewrite _fs_install to handle ghosts

    This was trying to handle ghosts, and failing hard at it. Now works with
    the same principle that all other ghost handling works with: discard the
    ghost extension internally, only append it when doing FS interactions.